# Site settings
title: Candid Giggles Photography
email: kimberly@candidgiggles.com
facebook: http://facebook.com/candidgiggles
instagram: https://www.instagram.com/candidgigglesphotography/
phone: 708.824.8538
description: > # this means to ignore newlines until "baseurl:"
  Kimberly Mitchell of Candid Giggles Photography specializes in children, high school seniors, portraits and family lifestyle photography.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "candidgiggles.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [vendor]
